# Setup
title:               The Transitive Experience of Plant Ownership
tagline:             'An idiot thinks in the woods'
description:         'The Personal Blog of one Bertrand Logan, a human trying to understand the world mostly unsuccessfully'
url:                 https://blog.bertrandlogan.com
baseurl:             ''
paginate:            15
permalink:           pretty

# About/contact
author:
  name:              Bertrand Logan
  url:               https://instagram.com/spidersdoingnothing
  email:             bertrandlogan42@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
google_analytics_id: UA-146052-15
