# Setup
title:               The Transitive Experience of Plant Ownership
tagline:             'If an Idiot thinks in a forest and their's no one there to hear him, is he still Stupid?'
description:         'The Personal Blog of one Bertrand Logan, an idiot stumbling through life.'
url:                 https://blog.bertrandlogan.com
baseurl:             ''
paginate:            15
permalink:           pretty

# About/contact
author:
  name:              Bertrand Logan
  url:               

# Gems
plugins:
  - jekyll-paginate

# Custom vars
#version:             1.1.0
#google_analytics_id: #UA-XXXX-Y
